name: CI
on: [push, pull_request]
jobs:
  lint:
    name: "Lint & Format Check"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8.5.1

      - uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: "pnpm"

      - name: Install deps
        run: pnpm install

      - name: Run ESLint
        run: pnpm lint

  e2e:
    name: "Build + E2E tests"
    env:
      NODE_ENV: test
      DATABASE_URL: "file:./prisma/dev.db"
      OPENEXCHANGERATES_API_KEY: ${{ secrets.OPENEXCHANGERATES_API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8.5.1

      - uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: "pnpm"

      - name: Install deps (with cache)
        run: pnpm install

      - name: Install playwright
        run: pnpm exec playwright install chromium

      - name: Next.js cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-nextjs

      - name: Setup database
        run: |
          pnpm prebuild
          pnpm prisma db push

      - name: Build
        run: pnpm build

      - name: Run E2E tests
        run: pnpm test-e2e

      - name: Check types
        run: pnpm tsc

      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            playwright/test-results

  unit:
    name: "Unit tests + typecheck"
    env:
      NODE_ENV: test
      DATABASE_URL: "file:./prisma/dev.db"
      OPENEXCHANGERATES_API_KEY: ${{ secrets.OPENEXCHANGERATES_API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8.5.1

      - uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: "pnpm"

      - name: Install deps (with cache)
        run: pnpm install

      - name: Next.js cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-nextjs

      - name: Setup database
        run: |
          pnpm prebuild
          pnpm prisma db push

      - name: Run unit tests
        run: pnpm test-unit

      - name: Check types
        run: pnpm tsc
